{
 "title": "Cisco Nexus 7000",
 "time": { "from": "2018-03-14T13:22:35.541Z", "to": "2018-04-04T13:54:25.565Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "nodeFilter(nodeSysOid == '.1.3.6.1.4.1.9.12.3.1.3.932')"
   },
   { "name": "snmpInterface", "query": "nodeResources($node)" },
   { "name": "ciscoNxEnv", "query": "nodeResources($node)" },
   { "name": "ciscoNxProc", "query": "nodeResources($node)" }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cisco System CPU Usage",
   "type": "timeseries",
   "description": "These statistics represent metrics collected from the Cisco Process MIB module which describes active system processes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "cpmCPUTotal5minRev", "name": "cpmCPUTotal5minRev" },
      "fallbackAttribute": {},
      "label": "cpmCPUTotal5minRev ($index)",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$ciscoNxProc", "label": "$ciscoNxProc" }
     },
     "label": "cpmCPUTotal5minRev ($index)",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Cisco System Memory Pools",
   "type": "timeseries",
   "description": "These statistics represent metrics collected from the Cisco Process MIB module which describes active system processes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "cpmCPUMemoryFree", "name": "cpmCPUMemoryFree" },
      "fallbackAttribute": {},
      "label": "cpmCPUMemoryFree_$index",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$ciscoNxProc", "label": "$ciscoNxProc" }
     },
     "label": "cpmCPUMemoryFree_$index",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "cpmCPUMemoryUsed", "name": "cpmCPUMemoryUsed" },
      "fallbackAttribute": {},
      "label": "cpmCPUMemoryUsed_$index",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "ciscoNXProcessIndex[22]", "label": "ciscoNXProcessIndex[22]" }
     },
     "label": "cpmCPUMemoryUsed_$index",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "expression": "cpmCPUMemoryFree_$index+cpmCPUMemoryUsed_$index",
     "label": "cpmCPUMemoryTotal_$index",
     "performanceType": { "label": "Expression", "value": 2 }
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "entSensorValue", "name": "entSensorValue" },
      "fallbackAttribute": {},
      "label": "$node ($index)",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$ciscoNxEnv", "label": "$ciscoNxEnv" }
     },
     "label": "$node ($index)",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "CPU Usage Modules",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "cpmCPUTotal5minRev", "name": "cpmCPUTotal5minRev" },
      "fallbackAttribute": {},
      "label": "$node ($index)",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$ciscoNxProc", "label": "$ciscoNxProc" }
     },
     "label": "$node ($index)",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Cisco Environment Monitors",
   "type": "timeseries",
   "description": "These statistics represent metrics collected from the Cisco Environmental sensors.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "entSensorValue", "name": "entSensorValue" },
      "fallbackAttribute": {},
      "label": "entSensorValue_$index",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$ciscoNxEnv", "label": "$ciscoNxEnv" }
     },
     "label": "entSensorValue_$index",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "description": "The total number of bits received and transmitted on the interface, including framing characters.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCInOctets", "name": "ifHCInOctets" },
      "fallbackAttribute": {},
      "label": "$index_in",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "$index_in",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    { "expression": "$index_in*8", "label": "In on $node $interface_$index", "performanceType": { "label": "Expression", "value": 2 } },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifOutOctets", "name": "ifOutOctets" },
      "fallbackAttribute": {},
      "label": "$index_out",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "$index_out",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    { "expression": "$index_out*8", "label": "Out on $node $interface_$index", "performanceType": { "label": "Expression", "value": 2 } }
   ]
  },
  {
   "title": "Interface Utilization",
   "type": "timeseries",
   "description": "Network interface utilisation.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCInOctets", "name": "ifHCInOctets" },
      "fallbackAttribute": {},
      "label": "$index_in",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "$index_in",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifOutOctets", "name": "ifOutOctets" },
      "fallbackAttribute": {},
      "label": "$index_out",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "$index_out",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    { "expression": "$index_in*8*100/1000000000", "label": "In $node on $interface_$index", "performanceType": { "label": "Expression", "value": 2 } },
    { "expression": "$index_out*8*100/1000000000", "label": "Out $node on $interface_$index", "performanceType": { "label": "Expression", "value": 2 } }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "For packet-oriented interfaces, the number of inbound or outbound packets that contained errors preventing them from being deliverable to a higher-layer protocol.  For character-oriented or fixed-length interfaces, the number of inbound transmission units that contained errors preventing them from being deliverable to a higher-layer protocol.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "ifInErrors", "name": "ifInErrors" },
      "fallbackAttribute": {},
      "label": "Out on $node $interface_$index",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "Out on $node $interface_$index",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "ifOutErrors", "name": "ifOutErrors" },
      "fallbackAttribute": {},
      "label": "In on $node $interface_$index",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "In on $node $interface_$index",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Discarded",
   "type": "timeseries",
   "description": "The number of outbound and inbound packets which were chosen to be discarded even though no errors had been detected to prevent their being deliverable to a higher-layer protocol. One possible reason for discarding such a packet could be to free up buffer space.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "ifInDiscards", "name": "ifInDiscards" },
      "fallbackAttribute": {},
      "label": "Out on $node $interface_$index",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "Out on $node $interface_$index",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "ifOutDiscards", "name": "ifOutDiscards" },
      "fallbackAttribute": {},
      "label": "In on $node $interface_$index",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "In on $node $interface_$index",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Packet Statistics",
   "type": "timeseries",
   "description": "Number of received or transmitted Unicast, Broadcast and Multicast packets.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "ifInUcastpkts", "name": "ifInUcastpkts" },
      "fallbackAttribute": {},
      "label": "In Unicast $node $interface ($index)",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "In Unicast $node $interface ($index)",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "ifInNUcastpkts", "name": "ifInNUcastpkts" },
      "fallbackAttribute": {},
      "label": "In Non-Unicast $node $interface ($index)",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "In Non-Unicast $node $interface ($index)",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "ifOutUcastPkts", "name": "ifOutUcastPkts" },
      "fallbackAttribute": {},
      "label": "Out Unicast $node $interface ($index)",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "Out Unicast $node $interface ($index)",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "ifOutNUcastPkts", "name": "ifOutNUcastPkts" },
      "fallbackAttribute": {},
      "label": "Out Non-Unicast $node $interface ($index)",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "$snmpInterface", "label": "$snmpInterface" }
     },
     "label": "Out Non-Unicast $node $interface ($index)",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  }
 ]
}