{
 "title": "OpenNMS Outage Wallboard",
 "description": "Information for about current alarms, outages, ​and affected business services from OpenNMS Horizon.",
 "tags": [ "opennms" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Monitoring Location",
    "query": "SELECT DISTINCT(n.location) FROM node n ORDER BY location ASC"
   },
   {
    "name": "category",
    "label": "Surveillance Category",
    "query": "SELECT 'no category'::TEXT as categoryname UNION SELECT categoryname FROM categories ORDER BY categoryname"
   }
  ]
 },
 "panels": [
  { "title": "Business Service Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "description": "Outstanding alarms related to business services.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*)\nFROM\n  alarms\nWHERE\n  alarms.eventuei = 'uei.opennms.org/bsm/serviceProblem' AND\n  alarms.alarmacktime isnull AND\n  alarms.logmsg not like '%resolved%'"
    }
   ]
  },
  {
   "title": "Business Service Alarms",
   "type": "table",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "filter": {
      "clauses": [
       {
        "operator": { "id": 1, "label": "AND" },
        "restriction": {
         "attribute": "uei",
         "comparator": { "id": 1, "label": "EQ" },
         "value": "uei.opennms.org/bsm/serviceProblem"
        }
       },
       {
        "operator": { "id": 1, "label": "AND" },
        "restriction": { "attribute": "alarmAckTime", "comparator": { "id": 1, "label": "EQ" }, "value": "null" }
       }
      ],
      "limit": 0
     },
     "rawSql": "SELECT\n  bsm_service.name,\n  bsmAlarm.lasteventtime,\n  EXTRACT(DAYS FROM age(now(), bsmAlarm.lasteventtime)) || 'd ' || EXTRACT(HOURS FROM age(now(), bsmAlarm.lasteventtime)) || 'h ' || EXTRACT(MINUTES FROM age(now(), bsmAlarm.lasteventtime)) || 'm ' || ROUND(EXTRACT(SECONDS FROM age(now(), bsmAlarm.lasteventtime))::NUMERIC,0) || 's' AS duration\nFROM\n  bsm_service\nJOIN\n  (SELECT\n    substring(reductionkey from '[0-9]+$')::INTEGER AS bsmId,\n    alarms.lasteventtime\n  FROM\n    alarms\n  WHERE\n    eventuei = 'uei.opennms.org/bsm/serviceProblem' and\n    alarms.logmsg not like '%resolved%') AS bsmAlarm\nON\n   bsmAlarm.bsmId = bsm_service.id\nORDER BY\n  bsmAlarm.lasteventtime DESC"
    }
   ]
  },
  { "title": "Alarms Outstanding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 7 },
   "content": "<h3 style=\"text-align: center\">Nodes</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 7 },
   "content": "<h3 style=\"text-align: center\">Interfaces</h3>"
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 7 },
   "content": "<h3 style=\"text-align: center\">Services</h3>"
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(current_node_alarms.nodeid)\nFROM\n  (SELECT\n    node_alarms.location,\n    node_alarms.nodeid,\n    node_alarms.lasteventtime,\n    $__timeTo() - node_alarms.firsteventtime AS duration_raw,\n    EXTRACT(DAYS FROM $__timeTo() - node_alarms.firsteventtime) || 'd ' || EXTRACT(HOURS FROM $__timeTo() - node_alarms.firsteventtime) || 'h ' || EXTRACT(MINUTES FROM $__timeTo() - node_alarms.firsteventtime) || 'm ' || ROUND(EXTRACT(SECONDS FROM $__timeTo() - node_alarms.firsteventtime)::NUMERIC,0) || 's' AS duration\n  FROM\n    node_alarms\n  WHERE\n    node_alarms.acknowledged = FALSE AND\n    node_alarms.eventuei like 'uei.opennms.org/nodes/nodeDown' AND\n    node_alarms.location IN ($location) AND\n    node_alarms.categoryname IN ($category) AND\n    node_alarms.max_alarm_severity_unack = '6'\n  GROUP BY\n    node_alarms.location,\n    node_alarms.nodelabel,\n    node_alarms.nodeid,\n    node_alarms.firsteventtime,\n    node_alarms.lasteventtime) AS current_node_alarms"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(current_interface_alarms.nodeid)\nFROM\n  (SELECT\n    node_alarms.location,\n    node_alarms.nodelabel,\n    node_alarms.nodeid,\n    node_alarms.ipaddr,\n    node_alarms.lasteventtime,\n    $__timeTo() - node_alarms.firsteventtime AS duration_raw,\n    EXTRACT(DAYS FROM $__timeTo() - node_alarms.firsteventtime) || 'd ' || EXTRACT(HOURS FROM $__timeTo() - node_alarms.firsteventtime) || 'h ' || EXTRACT(MINUTES FROM $__timeTo() - node_alarms.firsteventtime) || 'm ' || ROUND(EXTRACT(SECONDS FROM $__timeTo() - node_alarms.firsteventtime)::NUMERIC,0) || 's' AS duration\n  FROM\n    node_alarms\n  WHERE\n    node_alarms.acknowledged = FALSE AND\n    node_alarms.eventuei like 'uei.opennms.org/nodes/interfaceDown' AND\n    node_alarms.location IN ($location) AND\n    node_alarms.categoryname IN ($category) AND\n    node_alarms.max_alarm_severity_unack = '5'\n  GROUP BY\n    node_alarms.location,\n    node_alarms.nodeid,\n    node_alarms.nodelabel,\n    node_alarms.ipaddr,\n    node_alarms.firsteventtime,\n    node_alarms.lasteventtime) AS current_interface_alarms\n"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(current_service_alarms.nodeid)\nFROM\n  (SELECT\n    node_alarms.location,\n    node_alarms.nodelabel,\n    node_alarms.nodeid,\n    node_alarms.ipaddr,\n    node_alarms.servicename,\n    node_alarms.lasteventtime,\n    $__timeTo() - node_alarms.firsteventtime AS duration_raw,\n    EXTRACT(DAYS FROM $__timeTo() - node_alarms.firsteventtime) || 'd ' || EXTRACT(HOURS FROM $__timeTo() - node_alarms.firsteventtime) || 'h ' || EXTRACT(MINUTES FROM $__timeTo() - node_alarms.firsteventtime) || 'm ' || ROUND(EXTRACT(SECONDS FROM $__timeTo() - node_alarms.firsteventtime)::NUMERIC,0) || 's' AS duration\n  FROM\n    node_alarms\n  WHERE\n    node_alarms.acknowledged = FALSE AND\n    node_alarms.eventuei like 'uei.opennms.org/nodes/nodeLostService' AND\n    node_alarms.location IN ($location) AND\n    node_alarms.categoryname IN ($category) AND\n    node_alarms.max_alarm_severity_unack = '5'\n  GROUP BY\n    node_alarms.location,\n    node_alarms.nodeid,\n    node_alarms.nodelabel,\n    node_alarms.ipaddr,\n    node_alarms.servicename,\n    node_alarms.firsteventtime,\n    node_alarms.lasteventtime) AS current_service_alarms"
    }
   ]
  },
  { "title": "Outages Outstanding", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Current",
   "type": "singlestat",
   "description": "Current outages affecting nodes in selected categories or locations.",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  COUNT(DISTINCT(node_outages.nodeid)) AS amount\nFROM\n  node_outages\nWHERE\n  node_outages.resolved = 'FALSE' AND\n  node_outages.svclosteventuei = 'uei.opennms.org/nodes/nodeDown' AND\n  node_outages.location IN ($location) AND\n  node_outages.categoryname IN ($category)\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Percent",
   "type": "singlestat",
   "description": "Current outages affecting nodes in selected categories or locations in percent from the whole monitored inventory.",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN\n      nodes_by_category.tally > 0 THEN\n        100.0/nodes_by_category.tally * node_outages_by_category.tally\n      ELSE\n        0.0\n    END AS percentage\nFROM\n  (SELECT\n    'nodes'::TEXT AS type,\n    0.0 AS tally) AS tmp\nLEFT JOIN\n  (SELECT\n    'nodes'::TEXT AS type,\n    COUNT(distinct(nodeid)) AS tally\n  FROM\n    node_outages\n  WHERE\n    node_outages.location IN ($location) AND\n    node_outages.categoryname IN ($category) AND\n    node_outages.resolved = FALSE AND\n    node_outages.svclosteventuei = 'uei.opennms.org/nodes/nodeDown') AS node_outages_by_category\nON\n  node_outages_by_category.type = tmp.type\nLEFT JOIN\n  (SELECT\n    'nodes'::TEXT as type,\n    COUNT(DISTINCT(nodeid)) AS tally\n   FROM\n     node_categories\n   WHERE\n     node_categories.location IN ($location) AND\n     node_categories.categoryname IN ($category)\n  ) AS nodes_by_category\nON\n  nodes_by_category.type = tmp.type\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "All active monitored nodes in inventory.",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  COUNT(DISTINCT node_categories.nodeid)\nFROM\n  node_categories\nWHERE\n  node_categories.location IN ($location) AND\n  node_categories.categoryname IN ($category)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Current",
   "type": "singlestat",
   "description": "Current outages affecting nodes in selected categories or locations.",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  'ipinterfaces' :: TEXT AS type,\n  COUNT(distinct (node_outages.nodeid)) AS tally\nFROM\n  node_outages\nJOIN\n  node_outage_status\nON\n  node_outages.nodeid = node_outage_status.nodeid\nWHERE\n  node_outages.categoryname IN ($category) AND\n  node_outages.location IN ($location) AND\n  node_outages.resolved = FALSE AND\n  node_outages.nodetype = 'A' AND\n  node_outage_status.max_outage_severity = '5' AND\n  node_outages.svclosteventuei = 'uei.opennms.org/nodes/interfaceDown'",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Percentage",
   "type": "singlestat",
   "description": "Current outages affecting interfaces in selected categories or locations in percent from the whole monitored inventory.",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN\n      ipinterfaces_by_category.tally > 0 THEN\n        100.0/ipinterfaces_by_category.tally * ipinterfaces_outages_by_category.tally\n      ELSE\n        0.0\n    END AS percentage\nFROM\n  (SELECT\n    'ipinterfaces'::TEXT AS type,\n    0.0 AS tally) AS tmp\nLEFT JOIN\n  (SELECT\n    'ipinterfaces'::TEXT AS type,\n    COUNT(distinct (node_outages.nodeid)) AS tally\n  FROM\n    node_outages\n  JOIN\n    node_outage_status\n  ON\n    node_outages.nodeid = node_outage_status.nodeid\n  WHERE\n    node_outages.categoryname IN ($category) AND\n    node_outages.location IN ($location) AND\n    node_outages.resolved = FALSE AND\n    node_outages.nodetype = 'A' AND\n    node_outage_status.max_outage_severity = '5' AND\n    node_outages.svclosteventuei = 'uei.opennms.org/nodes/interfaceDown') AS ipinterfaces_outages_by_category\nON\n  ipinterfaces_outages_by_category.type = tmp.type\nLEFT JOIN\n  (SELECT\n    'ipinterfaces'::TEXT AS type,\n    COUNT(DISTINCT(nis.ip_if_id)) AS tally\n  FROM\n    node_ip_services nis\n  WHERE\n    nis.if_svc_status = 'A' AND\n    nis.categoryname IN ($category)) AS ipinterfaces_by_category\nON\n  ipinterfaces_by_category.type = tmp.type\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "All active monitored IP interfaces in inventory.",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  COUNT(DISTINCT(nis.ip_if_id)) AS tally\nFROM\n  node_ip_services nis\nWHERE\n  nis.if_svc_status = 'A' AND\n  nis.categoryname IN ($category) AND\n  nis.location IN ($location)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Current",
   "type": "singlestat",
   "description": "Current outages affecting services in selected categories or locations.",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  'services' :: TEXT AS type,\n  COUNT(DISTINCT (servicename)) AS tally\nFROM\n  node_outages\n  JOIN\n  node_outage_status\n    ON\n      node_outages.nodeid = node_outage_status.nodeid\nWHERE\n  node_outages.categoryname IN ($category) AND\n  node_outages.location IN ($location) AND\n  node_outages.resolved = FALSE AND\n  node_outages.nodetype = 'A' AND\n  node_outage_status.max_outage_severity = '5' AND\n  node_outages.svclosteventuei = 'uei.opennms.org/nodes/nodeLostService'\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Percentage",
   "type": "singlestat",
   "description": "Current outages affecting services in selected categories or locations in percent from the whole monitored inventory.",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 13 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN\n      services_by_category.tally > 0 THEN\n        100.0/services_by_category.tally * service_outages_by_category.tally\n      ELSE\n        0.0\n  END AS percentage\nFROM\n  (SELECT\n    'services'::TEXT AS type,\n    0.0 AS tally) AS tmp\nLEFT JOIN\n  (SELECT\n    'services'::TEXT AS type,\n    COUNT(DISTINCT(node_outages.serviceid)) AS tally\n  FROM\n    node_outages\n  JOIN\n    node_outage_status\n  ON\n    node_outages.nodeid = node_outage_status.nodeid\n  WHERE\n    node_outages.categoryname IN ($category) AND\n    node_outages.categoryname IN ($location) AND\n    node_outages.resolved = FALSE AND\n    node_outages.nodetype = 'A' AND\n    node_outage_status.max_outage_severity = '5' AND\n    node_outages.svclosteventuei = 'uei.opennms.org/nodes/nodeLostService') AS service_outages_by_category\nON\n  service_outages_by_category.type = tmp.type\nLEFT JOIN\n  (SELECT\n    'services'::TEXT as type,\n    COUNT(DISTINCT(node_ip_services.if_svc_id)) AS tally\n   FROM\n     node_ip_services\n   WHERE\n     node_ip_services.categoryname IN ($category) AND\n     node_ip_services.if_svc_status = 'A' ) AS services_by_category\nON\n  services_by_category.type = tmp.type\n"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "description": "All active monitored services in inventory.",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  COUNT(DISTINCT(nis.if_svc_id)) AS tally\nFROM\n  node_ip_services nis\nWHERE\n  nis.if_svc_status = 'A' AND\n  nis.categoryname IN ($category) AND\n  nis.location IN ($location)",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}