{
 "title": "OpenNMS Outage Statistics",
 "description": "Statistics about current outages with calculated availability and mean time to restore service in a custom time frame.",
 "tags": [
  "opennms",
  "mttr",
  "availability"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "OpenNMS Instance", "query": "postgres" },
   {
    "name": "location",
    "label": "Location",
    "query": "SELECT location FROM node_outages;"
   },
   {
    "name": "category",
    "label": "Surveillance Category",
    "query": "SELECT 'no category' UNION (SELECT categoryname FROM node_outages)"
   },
   {
    "name": "node",
    "label": "Node Label",
    "query": "SELECT nodelabel FROM node_outages"
   },
   {
    "name": "servicename",
    "label": "Service Name",
    "query": "SELECT DISTINCT(servicename) FROM node_outages"
   }
  ]
 },
 "panels": [
  {
   "title": "Outage Distribution",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('second', no.iflostservice) AS time,\n  0 AS value\nFROM\n  node_outages no\nWHERE\n  (no.iflostservice, COALESCE(no.ifregainedservice, to_timestamp($__unixEpochTo()))) OVERLAPS\n  (to_timestamp($__unixEpochFrom()), to_timestamp($__unixEpochTo())) AND\n  no.location IN ($location) AND\n  no.categoryname IN ($category) AND\n  no.nodelabel IN ($node) AND\n  no.servicename IN ($servicename)\nGROUP BY\n  no.iflostservice\n"
    }
   ]
  },
  { "title": "Network Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Node Availability",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "filter": {
      "clauses": [],
      "limit": 1000
     },
     "rawSql": "SELECT\n  nodelabel,\n  100.0 - SUM((100.0 * outage_duration_sec::DOUBLE PRECISION) / report_duration_sec::DOUBLE PRECISION) AS availability,\n  date_trunc('second', SUM(outages.outage_duration)) AS total_outage_time,\n  date_trunc('second', SUM(outages.outage_duration) / COUNT(svclosteventid)) AS mttr,\n  COUNT(svclosteventid) AS number_outages\nFROM\n  (SELECT\n    no.nodelabel,\n    no.duration AS outage_duration,\n    date_trunc('second', to_timestamp($__unixEpochTo()) - to_timestamp($__unixEpochFrom())) AS report_duration,\n    EXTRACT (EPOCH FROM date_trunc('second', to_timestamp($__unixEpochTo()) - to_timestamp($__unixEpochFrom()))) AS report_duration_sec,\n    EXTRACT (EPOCH FROM date_trunc('second', no.duration)) AS outage_duration_sec,\n    no.svclosteventid\n  FROM\n    node_outages no\n  WHERE\n    no.svclosteventuei = 'uei.opennms.org/nodes/nodeDown' AND\n    (no.iflostservice, COALESCE(no.ifregainedservice, to_timestamp($__unixEpochTo()))) OVERLAPS\n    (to_timestamp($__unixEpochFrom()), to_timestamp($__unixEpochTo())) AND\n    no.location IN ($location) AND\n    no.categoryname IN ($category) AND\n    no.nodelabel IN ($node) AND\n    no.servicename IN ($servicename)\n  GROUP BY\n    no.nodelabel,\n    no.svclosteventid,\n    outage_duration,\n    report_duration,\n    outage_duration_sec,\n    report_duration_sec) AS outages\nGROUP BY\n  nodelabel\nORDER BY\n  mttr ASC,\n  nodelabel ASC"
    }
   ]
  },
  { "title": "IP Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "IP Interface Availability",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "filter": {
      "clauses": [],
      "limit": 1000
     },
     "rawSql": "SELECT\n  nodelabel,\n  ipaddr,\n  100.0 - SUM((100.0 * outage_duration_sec::DOUBLE PRECISION) / report_duration_sec::DOUBLE PRECISION) AS availability,\n  date_trunc('second', SUM(outages.outage_duration)) AS total_outage_time,\n  date_trunc('second', SUM(outages.outage_duration) / COUNT(svclosteventid)) AS mttr,\n  COUNT(svclosteventid) AS number_outages\nFROM\n  (SELECT\n    no.nodelabel,\n    no.ipaddr,\n    no.duration AS outage_duration,\n    date_trunc('second', to_timestamp($__unixEpochTo()) - to_timestamp($__unixEpochFrom())) AS report_duration,\n    EXTRACT (EPOCH FROM date_trunc('second', to_timestamp($__unixEpochTo()) - to_timestamp($__unixEpochFrom()))) AS report_duration_sec,\n    EXTRACT (EPOCH FROM date_trunc('second', no.duration)) AS outage_duration_sec,\n    no.svclosteventid\n  FROM\n    node_outages no\n  WHERE\n    no.svclosteventuei = 'uei.opennms.org/nodes/interfaceDown' AND\n    (no.iflostservice, COALESCE(no.ifregainedservice, to_timestamp($__unixEpochTo()))) OVERLAPS\n    (to_timestamp($__unixEpochFrom()), to_timestamp($__unixEpochTo())) AND\n    no.location IN ($location) AND\n    no.categoryname IN ($category) AND\n    no.nodelabel IN ($node) AND\n    no.servicename IN ($servicename)\n  GROUP BY\n    no.nodelabel,\n    no.ipaddr,\n    no.svclosteventid,\n    outage_duration,\n    report_duration,\n    outage_duration_sec,\n    report_duration_sec) AS outages\nGROUP BY\n  nodelabel,\n  ipaddr\nORDER BY\n  mttr ASC,\n  nodelabel ASC,\n  ipaddr ASC"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Service Availability",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "filter": {
      "clauses": [],
      "limit": 1000
     },
     "rawSql": "SELECT\n  nodelabel,\n  ipaddr,\n  servicename,\n  100.0 - SUM((100.0 * outage_duration_sec::DOUBLE PRECISION) / report_duration_sec::DOUBLE PRECISION) AS availability,\n  date_trunc('second', SUM(outages.outage_duration)) AS total_outage_time,\n  date_trunc('second', SUM(outages.outage_duration) / COUNT(svclosteventid)) AS mttr,\n  COUNT(svclosteventid) AS number_outages\nFROM\n  (SELECT\n    no.nodelabel,\n    no.ipaddr,\n    no.servicename,\n    no.duration AS outage_duration,\n    date_trunc('second', to_timestamp($__unixEpochTo()) - to_timestamp($__unixEpochFrom())) AS report_duration,\n    EXTRACT (EPOCH FROM date_trunc('second', to_timestamp($__unixEpochTo()) - to_timestamp($__unixEpochFrom()))) AS report_duration_sec,\n    EXTRACT (EPOCH FROM date_trunc('second', no.duration)) AS outage_duration_sec,\n    no.svclosteventid\n  FROM\n    node_outages no\n  WHERE\n    no.svclosteventuei = 'uei.opennms.org/nodes/nodeLostService' AND\n    (no.iflostservice, COALESCE(no.ifregainedservice, to_timestamp($__unixEpochTo()))) OVERLAPS\n    (to_timestamp($__unixEpochFrom()), to_timestamp($__unixEpochTo())) AND\n    no.location IN ($location) AND\n    no.categoryname IN ($category) AND\n    no.nodelabel IN ($node) AND\n    no.servicename IN ($servicename)\n  GROUP BY\n    no.nodelabel,\n    no.ipaddr,\n    no.servicename,\n    no.svclosteventid,\n    outage_duration,\n    report_duration,\n    outage_duration_sec,\n    report_duration_sec) AS outages\nGROUP BY\n  nodelabel,\n  ipaddr,\n  servicename\nORDER BY\n  mttr ASC,\n  nodelabel ASC,\n  ipaddr ASC,\n  servicename ASC"
    }
   ]
  }
 ]
}