{
 "title": "Linux Server Heatmap",
 "description": "Heatmap for Linux server based on SNMP collected with OpenNMS. The heatmap uses Load 5 min. average and normalized using the CPU number count. Memory, CPU, and Disk load 5 min. average in %.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "OpenNMS Instance", "query": "opennms-performance-datasource" },
   {
    "name": "node",
    "label": "Node",
    "query": "nodeFilter(nodeSysOID LIKE '.1.3.6.1.4.1.8072.3.2.10' & serviceName like 'SNMP' & !(ipaddr iplike 10.10.15.*)& !(ipaddr iplike 10.10.9.*))"
   },
   { "name": "disk", "query": "nodeResources($node)" }
  ]
 },
 "panels": [
  {
   "title": "Heatmap: $node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "targets": [
    {}
   ]
  },
  {
   "title": "Load average 5 min",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "loadavg5", "name": "loadavg5" },
      "fallbackAttribute": {},
      "label": "loadavg",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "loadavg",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuNumCpus", "name": "CpuNumCpus" },
      "fallbackAttribute": {},
      "label": "numcpus",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "numcpus",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "expression": "((  loadavg / 100 ) / numcpus * 100.0)",
     "label": "Load in %",
     "performanceType": { "label": "Expression", "value": 2 }
    }
   ]
  },
  {
   "title": "CPU",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawUser", "name": "CpuRawUser" },
      "fallbackAttribute": {},
      "label": "CpuRawUser",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "CpuRawUser",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawNice", "name": "CpuRawNice" },
      "fallbackAttribute": {},
      "label": "CpuRawNice",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "CpuRawNice",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawSystem", "name": "CpuRawSystem" },
      "fallbackAttribute": {},
      "label": "CpuRawSystem",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "CpuRawSystem",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawIdle", "name": "CpuRawIdle" },
      "fallbackAttribute": {},
      "label": "CpuRawIdle",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "CpuRawIdle",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "expression": "(( CpuRawUser + CpuRawNice + CpuRawSystem )   / ( CpuRawUser + CpuRawNice  + CpuRawSystem + CpuRawIdle ) * 100.0)",
     "label": "CPU in %",
     "performanceType": { "label": "Expression", "value": 2 }
    }
   ]
  },
  {
   "title": "Memory",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memTotalReal", "name": "memTotalReal" },
      "fallbackAttribute": {},
      "label": "memTotalReal",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "memTotalReal",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memAvailReal", "name": "memAvailReal" },
      "fallbackAttribute": {},
      "label": "memAvailReal",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "memAvailReal",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memBuffer", "name": "memBuffer" },
      "fallbackAttribute": {},
      "label": "memBuffer",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "memBuffer",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memCached", "name": "memCached" },
      "fallbackAttribute": {},
      "label": "memCached",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "memCached",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrMemorySize", "name": "hrMemorySize" },
      "fallbackAttribute": {},
      "label": "hrMemorySize",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "hrMemorySize",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "expression": "(memTotalReal-memAvailReal-memBuffer-memCached)/hrMemorySize*100",
     "label": "Memory in %",
     "performanceType": { "label": "Expression", "value": 2 }
    }
   ]
  },
  {
   "title": "Disk: $disk",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "diskIOLA5", "name": "diskIOLA5" },
      "fallbackAttribute": {},
      "label": "Disk Load in %",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "diskIOIndex[$disk]", "label": "diskIOIndex[$disk]" }
     },
     "label": "Disk Load in %",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  }
 ]
}