{
 "title": "Linux Node performance metrics",
 "description": "Display basic SNMP data collected on Linux hosts with OpenNMS >= 25.2.x for use with OpenNMS Helm 5.0.0 in Grafana 6.6 (optionally with R for trendlines).",
 "time": { "from": "now-24h", "to": "now-6m" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "opennms-performance-datasource" },
   { "name": "node", "query": "nodeFilter(isSNMP)" },
   { "name": "disk", "query": "nodeResources($node)" },
   { "name": "partition", "query": "nodeResources($node)" },
   { "name": "interface", "query": "nodeResources($node)" },
   { "name": "hrStorage", "query": "nodeResources($node)" },
   { "name": "lmTempIndex" }
  ]
 },
 "panels": [
  {
   "title": "Load (5min)",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "AVERAGE" },
      "attribute": { "label": "loadavg5", "name": "loadavg5" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    { "expression": "loadavg5 / 100", "label": "Load (Avg)", "performanceType": { "label": "Expression", "value": 2 } }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrSystemProcesses", "name": "hrSystemProcesses" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrSystemNumUsers", "name": "hrSystemNumUsers" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrSystemUptime", "name": "hrSystemUptime" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    { "expression": "hrSystemUptime / 100", "label": "Uptime", "performanceType": { "label": "Expression", "value": 2 } }
   ]
  },
  {
   "title": "CPU usage and Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage ($node)",
   "type": "timeseries",
   "description": "**ssCpuRawUser**: The number of 'ticks' (typically 1/100s) spent processing user-level code.\n\n**ssCpuRawNice**: The number of 'ticks' (typically 1/100s) spent processing reduced-priority code. This object will not be implemented on hosts where the underlying operating system does not measure this particular CPU metric.\n\n**ssCpuRawSystem**: The number of 'ticks' (typically 1/100s) spent processing system-level code.\n\nThis object may sometimes be implemented as the combination of the 'ssCpuRawWait(54)' and 'ssCpuRawKernel(55)' counters, so care must be taken when summing the overall raw counters.\n\n**ssCpuRawIdle**: The number of 'ticks' (typically 1/100s) spent idle.\n\n**ssCpuRawWait**: The number of 'ticks' (typically 1/100s) spent waiting for IO.\n\nThis object will not be implemented on hosts where the underlying operating system does not measure this particular CPU metric.  This time may also be included within the 'ssCpuRawSystem(52)' counter.\n\n**ssCpuRawKernel**: The number of 'ticks' (typically 1/100s) spent processing kernel-level code.\n\nThis object will not be implemented on hosts where the underlying operating system does not measure this particular CPU metric.  This time may also be included within the 'ssCpuRawSystem(52)' counter.\n\n**ssCpuRawInterrupt**: The number of 'ticks' (typically 1/100s) spent processing hardware interrupts.\n\nThis object will not be implemented on hosts where the underlying operating system does not measure this particular CPU metric.\n\n**ssCpuRawSteal**: The number of 'ticks' (typically 1/100s) spent by the hypervisor code to run other VMs even though the CPU in the current VM had something runnable.\n\nThis object will not be implemented on hosts where the underlying operating system does not measure this particular CPU metric.\n\n**ssCpuRawSteal**: The number of 'ticks' (typically 1/100s) spent by the CPU to run a virtual CPU (guest).\n\nThis object will not be implemented on hosts where the underlying operating system does not measure this particular CPU metric.\n\n**ssCpuRawGuestNice**: The number of 'ticks' (typically 1/100s) spent by the CPU to run a niced virtual CPU (guest).\n\nThis object will not be implemented on hosts where the underlying operating system does not measure this particular CPU metric.\n\nOn a multi-processor system, the 'ssCpuRaw*'  ounters are cumulative over all CPUs, so their  sum will typically be N*100 (for N processors).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawIdle", "name": "CpuRawIdle" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawInterrupt", "name": "CpuRawInterrupt" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawKernel", "name": "CpuRawKernel" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawNice", "name": "CpuRawNice" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawSoftIRQ", "name": "CpuRawSoftIRQ" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawSystem", "name": "CpuRawSystem" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawUser", "name": "CpuRawUser" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawWait", "name": "CpuRawWait" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawGuest", "name": "CpuRawGuest" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawGuestNice", "name": "CpuRawGuestNice" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawSteal", "name": "CpuRawSteal" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Load averages ($node)",
   "type": "timeseries",
   "description": "**laLoadFloat**: The 1,5 and 15 minute load averages as an opaquely wrapped floating point number.\n\n**laLoadInt**: The 1,5 and 15 minute load averages as an integer. This is computed by taking the floating point loadaverage value and multiplying by 100, then converting the value to an integer.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "loadavg1", "name": "loadavg1" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "loadavg5", "name": "loadavg5" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "loadavg15", "name": "loadavg15" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    { "expression": "loadavg1 / 100", "label": "1min avg.", "performanceType": { "label": "Expression", "value": 2 } },
    { "expression": "loadavg5 / 100", "label": "5min avg.", "performanceType": { "label": "Expression", "value": 2 } },
    { "expression": "loadavg15 / 100", "label": "15min avg.", "performanceType": { "label": "Expression", "value": 2 } },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawIdle", "name": "CpuRawIdle" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawInterrupt", "name": "CpuRawInterrupt" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawKernel", "name": "CpuRawKernel" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawNice", "name": "CpuRawNice" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawSoftIRQ", "name": "CpuRawSoftIRQ" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawSystem", "name": "CpuRawSystem" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawUser", "name": "CpuRawUser" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawWait", "name": "CpuRawWait" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawGuest", "name": "CpuRawGuest" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawGuestNice", "name": "CpuRawGuestNice" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuRawSteal", "name": "CpuRawSteal" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 },
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "CpuNumCpus", "name": "CpuNumCpus" },
      "fallbackAttribute": {},
      "label": "Number of CPUs",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "Number of CPUs",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Memory and swap usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage ($node)",
   "type": "timeseries",
   "description": "**memTotalSwap**: The total amount of swap space configured for this host.\n\n**memAvailSwap**: The amount of swap space currently unused or available.\n\n**memTotalReal**: The total amount of real/physical memory installed on this host.\n\n**memAvailReal**: The amount of real/physical memory currently unused or available.\n\n**memShared**: The total amount of real or virtual memory currently allocated for use as shared memory.\n\nThis object will not be implemented on hosts where the underlying operating system does not explicitly identify memory as specifically reserved for this purpose.\n\n**memBuffer**: The total amount of real or virtual memory currently allocated for use as memory buffers.\n\nThis object will not be implemented on hosts where the underlying operating system does not explicitly identify memory as specifically reserved for this purpose.\n\n**memCached**: The total amount of real or virtual memory currently allocated for use as cached memory.\n\nThis object will not be implemented on hosts where the underlying operating system does not explicitly identify memory as specifically reserved for this purpose.",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memAvailSwap", "name": "memAvailSwap" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memAvailReal", "name": "memAvailReal" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memTotalSwap", "name": "memTotalSwap" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    { "expression": "memTotalSwap - memAvailSwap", "label": "memUsedSwap", "performanceType": { "label": "Expression", "value": 2 } },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memBuffer", "name": "memBuffer" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memCached", "name": "memCached" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": { "attribute": { "name": "memTotalReal" } },
     "expression": "memTotalReal - memShared - memBuffer - memAvailReal - memCached",
     "label": "memUsed",
     "performanceType": { "label": "Expression", "value": 2 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memShared", "name": "memShared" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memTotalReal", "name": "memTotalReal" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "description": "**memTotalSwap**: The total amount of swap space configured for this host.\n\n**memAvailSwap**: The amount of swap space currently unused or available.\n\n**memTotalReal**: The total amount of real/physical memory installed on this host.\n\n**memAvailReal**: The amount of real/physical memory currently unused or available.\n\n**memShared**: The total amount of real or virtual memory currently allocated for use as shared memory.\n\nThis object will not be implemented on hosts where the underlying operating system does not explicitly identify memory as specifically reserved for this purpose.\n\n**memBuffer**: The total amount of real or virtual memory currently allocated for use as memory buffers.\n\nThis object will not be implemented on hosts where the underlying operating system does not explicitly identify memory as specifically reserved for this purpose.\n\n**memCached**: The total amount of real or virtual memory currently allocated for use as cached memory.\n\nThis object will not be implemented on hosts where the underlying operating system does not explicitly identify memory as specifically reserved for this purpose.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memTotalReal", "name": "memTotalReal" },
      "fallbackAttribute": {},
      "label": "memTotalReal",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "memTotalReal",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memTotalFree", "name": "memTotalFree" },
      "fallbackAttribute": {},
      "label": "memTotalFree",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "memTotalFree",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memBuffer", "name": "memBuffer" },
      "fallbackAttribute": {},
      "label": "memBuffer",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "memBuffer",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "memCached", "name": "memCached" },
      "fallbackAttribute": {},
      "label": "memCached",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "memCached",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "expression": "((memTotalFree + memBuffer + memCached) / memTotalReal ) * 100.0",
     "label": "Usage",
     "performanceType": { "label": "Expression", "value": 2 }
    }
   ]
  },
  {
   "title": "Disk utilization ($disk)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "disk",
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk load ($disk)",
   "type": "timeseries",
   "description": "**diskIOLA1**: The 1 minute average load of disk (%).\n\n**diskIOLA5**: The 5 minute average load of disk (%).\n\n**diskIOLA15**: The 15 minute average load of disk (%).",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "diskIOLA1", "name": "diskIOLA1" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "diskIOIndex[$disk]", "label": "diskIOIndex[$disk]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "diskIOLA5", "name": "diskIOLA5" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "diskIOIndex[$disk]", "label": "diskIOIndex[$disk]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "diskIOLA15", "name": "diskIOLA15" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "diskIOIndex[$disk]", "label": "diskIOIndex[$disk]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Disk I/O accesses ($disk)",
   "type": "timeseries",
   "description": "**diskIOReads**: The number of read accesses to this device since boot.\n\n**diskIOWrites**: The number of write accesses to this device since boot.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "diskIOReads", "name": "diskIOReads" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "diskIOIndex[$disk]", "label": "diskIOIndex[$disk]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "diskIOWrites", "name": "diskIOWrites" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "diskIOIndex[$disk]", "label": "diskIOIndex[$disk]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Disk I/O bytes ($disk)",
   "type": "timeseries",
   "description": "**diskIOReadX**: The number of bytes read from this device since boot.\n\n**diskIOWrittenX**: The number of bytes written from this device since boot.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "diskIONReadX", "name": "diskIONReadX" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "diskIOIndex[$disk]", "label": "diskIOIndex[$disk]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "diskIONWrittenX", "name": "diskIONWrittenX" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "diskIOIndex[$disk]", "label": "diskIOIndex[$disk]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Context Switches and Interrupts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Context Switches and Interrupts ($node)",
   "type": "timeseries",
   "description": "**ssRawInterrupts**: Number of interrupts processed\n\n**ssRawContexts**: Number of context switches",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "SysContext", "name": "SysContext" },
      "fallbackAttribute": {},
      "label": "SysContext",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "SysContext",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "SysInterrupts", "name": "SysInterrupts" },
      "fallbackAttribute": {},
      "label": "SysInterrupts",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "SysInterrupts",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "SysRawContext", "name": "SysRawContext" },
      "fallbackAttribute": {},
      "label": "SysRawContext",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "SysRawContext",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "SysRawInterrupts", "name": "SysRawInterrupts" },
      "fallbackAttribute": {},
      "label": "SysRawInterrupts",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "label": "SysRawInterrupts",
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "$interface ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "repeat": "interface",
   "targets": [
    {}
   ]
  },
  {
   "title": "Octets transmitted",
   "type": "timeseries",
   "description": "The total number of octets transmitted out of the interface, including framing characters. These objects are a 64-bit versions of if{Out,In}Octets.\n\nDiscontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by the value of ifCounterDiscontinuityTime.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCInOctets", "name": "ifHCInOctets" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCOutOctets", "name": "ifHCOutOctets" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Packets transmitted",
   "type": "timeseries",
   "description": "The total number of packets that higher-level protocols requested be transmitted, which were either unicast, multicast, or broadcast packets, including those that were discarded or not sent. These objects are 64-bit versions of if{Out,In}{U,Multi}castPkts. \n\nDiscontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by the value of ifCounterDiscontinuityTime.",
   "gridPos": { "h": 11, "w": 10, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCInBroadcastPkts", "name": "ifHCInBroadcastPkts" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCInMulticastPkts", "name": "ifHCInMulticastPkts" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCInUcastPkts", "name": "ifHCInUcastPkts" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCOutBroadcastPkt", "name": "ifHCOutBroadcastPkt" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCOutMulticastPkt", "name": "ifHCOutMulticastPkt" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifHCOutUcastPkts", "name": "ifHCOutUcastPkts" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Errors and discards",
   "type": "timeseries",
   "description": "ifInDiscards: The number of inbound packets which were chosen to be discarded even though no errors had been detected to prevent their being deliverable to a higher-layer protocol. One possible reason for discarding such a packet could be to free up buffer space. \n\nIfInErrors: For packet-oriented interfaces, the number of inbound packets that contained errors preventing them from being deliverable to a higher-layer protocol. For character- oriented or fixed-length interfaces, the number of inbound transmission units that contained errors preventing them from being deliverable to a higher-layer protocol.\n\nifOutDiscards: The number of outbound packets which were chosen to be discarded even though no errors had been detected to prevent their being transmitted. One possible reason for discarding such a packet could be to free up buffer space.\n\nIfOutErrors: For packet-oriented interfaces, the number of outbound packets that could not be transmitted because of errors. For character-oriented or fixed-length interfaces, the number of outbound transmission units that could not be transmitted because of errors.\n\nDiscontinuities in the value of these counters can occur at re-initialization of the management system, and at other times as indicated by the value of ifCounterDiscontinuityTime.",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifInErrors", "name": "ifInErrors" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifOutErrors", "name": "ifOutErrors" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifInDiscards", "name": "ifInDiscards" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ifOutDiscards", "name": "ifOutDiscards" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "interfaceSnmp[$interface]", "label": "interfaceSnmp[$interface]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Raw IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1435 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Raw IO ($node)",
     "type": "graph",
     "description": "ssIORawSent: Number of blocks sent to a block device\n\nssIORawReceived: Number of blocks received from a block device",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "iops", "label": "Blocks per second" }
     ],
     "targets": [
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "IORawReceived", "name": "IORawReceived" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      },
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "IORawSent", "name": "IORawSent" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      }
     ]
    }
   ]
  },
  {
   "title": "Memory and swap usage (split)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1436 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Swap usage ($node)",
     "type": "graph",
     "description": "**memTotalSwap**: The total amount of swap space configured for this host.\n\n**memAvailSwap**: The amount of swap space currently unused or available.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "kbytes" }
     ],
     "targets": [
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "memAvailSwap", "name": "memAvailSwap" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      },
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "memSwapError", "name": "memSwapError" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      },
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "memTotalSwap", "name": "memTotalSwap" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      },
      { "expression": "memTotalSwap - memAvailSwap", "label": "memUsedSwap", "performanceType": { "label": "Expression", "value": 2 } }
     ]
    },
    {
     "title": "Memory usage ($node)",
     "type": "graph",
     "description": "**memTotalReal**: The total amount of real/physical memory installed on this host.\n\n**memAvailReal**: The amount of real/physical memory currently unused or available.\n\n**memShared**: The total amount of real or virtual memory currently allocated for use as shared memory.\n\nThis object will not be implemented on hosts where the underlying operating system does not explicitly identify memory as specifically reserved for this purpose.\n\n**memBuffer**: The total amount of real or virtual memory currently allocated for use as memory buffers.\n\nThis object will not be implemented on hosts where the underlying operating system does not explicitly identify memory as specifically reserved for this purpose.\n\n**memCached**: The total amount of real or virtual memory currently allocated for use as cached memory.\n\nThis object will not be implemented on hosts where the underlying operating system does not explicitly identify memory as specifically reserved for this purpose.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "yaxes": [
      { "format": "deckbytes" }
     ],
     "targets": [
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "memShared", "name": "memShared" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      },
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "memCached", "name": "memCached" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      },
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "memBuffer", "name": "memBuffer" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      },
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "memAvailReal", "name": "memAvailReal" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      },
      {
       "attribute": { "attribute": { "name": "memTotalReal" } },
       "expression": "memTotalReal - memShared - memBuffer - memCached - memAvailReal",
       "label": "memUsed",
       "performanceType": { "label": "Expression", "value": 2 }
      },
      {
       "attribute": {
        "aggregation": { "label": "" },
        "attribute": { "label": "memTotalReal", "name": "memTotalReal" },
        "fallbackAttribute": {},
        "label": "",
        "node": { "id": "$node", "label": "$node" },
        "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
       },
       "performanceType": { "label": "Attribute", "value": 1 }
      }
     ]
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1437 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk usage ($partition)",
   "type": "piechart",
   "description": "dskAvail: Available space on the disk. For large lightly-used disks (>2Tb), this value will latch at INT32_MAX (2147483647).\n\ndskUsed: Used space on the disk. For large heavily-used disks (>2Tb), this value will latch at INT32_MAX (2147483647).",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1438 },
   "repeat": "partition",
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ns-dskAvail", "name": "ns-dskAvail" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "dskIndex[$partition]", "label": "dskIndex[$partition]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ns-dskUsed", "name": "ns-dskUsed" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "dskIndex[$partition]", "label": "dskIndex[$partition]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Disk usage ($partition)",
   "type": "timeseries",
   "description": "**dskTotal**: Total size of the disk/partion (kBytes). For large disks (>2Tb), this value will latch at INT32_MAX (2147483647).\n\n**dskUsed**: Used space on the disk. For large heavily-used disks (>2Tb), this value will latch at INT32_MAX (2147483647).\n\n**dskTrend**: Linear prediction for next 16 hours.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1446 },
   "repeat": "partition",
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ns-dskUsed", "name": "ns-dskUsed" },
      "fallbackAttribute": {},
      "label": "dskUsed",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "dskIndex[$partition]", "label": "dskIndex[$partition]" }
     },
     "label": "dskUsed",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "ns-dskTotal", "name": "ns-dskTotal" },
      "fallbackAttribute": {},
      "label": "dskTotal",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "dskIndex[$partition]", "label": "dskIndex[$partition]" }
     },
     "label": "dskTotal",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "filter": {
      "backend": "R",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.TrendLine",
      "description": "Fits a trend line or polynomial to a given column.",
      "label": "Trend",
      "name": "Trend",
      "parameter": [
       {
        "description": "Input column.",
        "displayName": "Input",
        "key": "inputColumn",
        "required": true,
        "type": "string"
       },
       {
        "description": "Output column.",
        "displayName": "Output",
        "key": "outputColumn",
        "required": true,
        "type": "string"
       },
       {
        "default": "0",
        "description": "Number seconds ahead the of the column for which we want to include the trend line.",
        "displayName": "Forecast",
        "key": "secondsAhead",
        "required": true,
        "type": "long"
       },
       {
        "default": "1",
        "description": "Polynomial order of the trend line/curve. Set this to 1 for a line.",
        "displayName": "Order",
        "key": "polynomialOrder",
        "required": true,
        "type": "int"
       }
      ]
     },
     "filterState": {
      "inputColumn": {
       "filter": {
        "description": "Input column.",
        "displayName": "Input",
        "key": "inputColumn",
        "required": true,
        "type": "string"
       },
       "value": "dskUsed"
      },
      "outputColumn": {
       "filter": {
        "description": "Output column.",
        "displayName": "Output",
        "key": "outputColumn",
        "required": true,
        "type": "string"
       },
       "value": "dskTrend"
      },
      "secondsAhead": {
       "filter": {
        "description": "Number seconds ahead the of the column for which we want to include the trend line.",
        "displayName": "Forecast",
        "key": "secondsAhead",
        "required": true,
        "type": "long"
       },
       "value": "57600"
      }
     },
     "performanceType": { "label": "Filter", "value": 3 }
    }
   ]
  },
  {
   "title": "Swap statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1464 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Swap usage ($node)",
   "type": "timeseries",
   "description": "ssSwapIn: The average amount of memory swapped in from disk, calculated over the last minute.\n\nssSwapOut: The average amount of memory swapped out to disk, calculated over the last minute.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1465 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "SwapIn", "name": "SwapIn" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "SwapOut", "name": "SwapOut" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    { "expression": "SwapIn * 1024 / 60", "label": "Swap in", "performanceType": { "label": "Expression", "value": 2 } },
    { "expression": "SwapOut * 1024 / 60", "label": "Swap Out", "performanceType": { "label": "Expression", "value": 2 } }
   ]
  },
  {
   "title": "Swap space ($node)",
   "type": "timeseries",
   "description": "hrStorageAllocationUnits: The size, in bytes, of the data objects allocated from this pool.  If this entry is monitoring sectors, blocks, buffers, or packets, for example, this number will commonly be greater than one.  Otherwise this number will typically be one.\n\nhrStorageSize: The size of the storage represented by this entry, in units of hrStorageAllocationUnits. This object is writable to allow remote configuration of the size of the storage area in those cases where such an operation makes sense and is possible on the underlying system. For example, the amount of main memory allocated to a buffer pool might be modified or\nthe amount of disk space allocated to virtual memory might be modified.\n\nhrStorageUsed: The amount of the storage represented by this entry that is allocated, in units of hrStorageAllocationUnits.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1465 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrStorageAllocUnits", "name": "hrStorageAllocUnits" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "hrStorageIndex[Swapspace]", "label": "hrStorageIndex[Swapspace]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrStorageSize", "name": "hrStorageSize" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "hrStorageIndex[Swapspace]", "label": "hrStorageIndex[Swapspace]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrStorageUsed", "name": "hrStorageUsed" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "hrStorageIndex[Swapspace]", "label": "hrStorageIndex[Swapspace]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "expression": "hrStorageAllocUnits * hrStorageUsed",
     "label": "Used",
     "performanceType": { "label": "Expression", "value": 2 }
    },
    {
     "filter": {
      "backend": "R",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.TrendLine",
      "description": "Fits a trend line or polynomial to a given column.",
      "label": "Trend",
      "name": "Trend",
      "parameter": [
       {
        "description": "Input column.",
        "displayName": "Input",
        "key": "inputColumn",
        "required": true,
        "type": "string"
       },
       {
        "description": "Output column.",
        "displayName": "Output",
        "key": "outputColumn",
        "required": true,
        "type": "string"
       },
       {
        "default": "0",
        "description": "Number seconds ahead the of the column for which we want to include the trend line.",
        "displayName": "Forecast",
        "key": "secondsAhead",
        "required": true,
        "type": "long"
       },
       {
        "default": "1",
        "description": "Polynomial order of the trend line/curve. Set this to 1 for a line.",
        "displayName": "Order",
        "key": "polynomialOrder",
        "required": true,
        "type": "int"
       }
      ]
     },
     "filterState": {
      "inputColumn": {
       "filter": {
        "description": "Input column.",
        "displayName": "Input",
        "key": "inputColumn",
        "required": true,
        "type": "string"
       },
       "value": "Used"
      },
      "outputColumn": {
       "filter": {
        "description": "Output column.",
        "displayName": "Output",
        "key": "outputColumn",
        "required": true,
        "type": "string"
       },
       "value": "Trend"
      },
      "polynomialOrder": {
       "filter": {
        "description": "Polynomial order of the trend line/curve. Set this to 1 for a line.",
        "displayName": "Order",
        "key": "polynomialOrder",
        "required": true,
        "type": "int"
       },
       "value": "1"
      },
      "secondsAhead": {
       "filter": {
        "description": "Number seconds ahead the of the column for which we want to include the trend line.",
        "displayName": "Forecast",
        "key": "secondsAhead",
        "required": true,
        "type": "long"
       },
       "value": "7200"
      }
     },
     "performanceType": { "label": "Filter", "value": 3 }
    },
    {
     "expression": "hrStorageAllocUnits * hrStorageSize",
     "label": "Size",
     "performanceType": { "label": "Expression", "value": 2 }
    }
   ]
  },
  {
   "title": "TCP statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1472 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TCP connections ($node)",
   "type": "timeseries",
   "description": "tcpActiveOpens: The number of times that TCP connections have made a direct transition to the SYN-SENT state from the CLOSED state. \n\ntcpPassiveOpens: The number of times TCP connections have made a direct transition to the SYN-RCVD state from the LISTEN state.\n\nDiscontinuities in the value of these counters are indicated via discontinuities in the value of sysUpTime.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1473 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "tcpActiveOpens", "name": "tcpActiveOpens" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "tcpPassiveOpens", "name": "tcpPassiveOpens" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "tcpEstabResets", "name": "tcpEstabResets" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "tcpOutRsts", "name": "tcpOutRsts" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "TCP Segments ($node)",
   "type": "timeseries",
   "description": "tcpOutSegs: The total number of segments sent, including those on current connections but excluding those containing only retransmitted octets.\n\ntcpInSegs: The total number of segments received, including those received in error. This count includes segments received on currently established connections.\n\nDiscontinuities in the value of these counters are indicated via discontinuities in the value of sysUpTime.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1473 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "tcpInSegs", "name": "tcpInSegs" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "tcpOutSegs", "name": "tcpOutSegs" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "TCP errors ($node)",
   "type": "timeseries",
   "description": "Discontinuities in the value of these counters are indicated via discontinuities in the value of sysUpTime.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1473 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "tcpAttemptFails", "name": "tcpAttemptFails" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "tcpInErrors", "name": "tcpInErrors" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "tcpRetransSegs", "name": "tcpRetransSegs" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "UDP statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1481 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UDP datagrams ($node)",
   "type": "timeseries",
   "description": "**udpOutDatagrams**: The total number of UDP datagrams sent from this entity.\n\nDiscontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by discontinuities in the value of sysUpTime.\n\n**udpInDatagrams**: The total number of UDP datagrams delivered to UDP users.\n\nDiscontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by discontinuities in the value of sysUpTime.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1482 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "udpInDatagrams", "name": "udpInDatagrams" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "udpOutDatagrams", "name": "udpOutDatagrams" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "UDP errors ($node)",
   "type": "timeseries",
   "description": "**udpNoPorts**: The total number of received UDP datagrams for which there was no application at the destination port.\n\nDiscontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by discontinuities in the value of sysUpTime.\n\n**udpInErrors**: The number of received UDP datagrams that could not be delivered for reasons other than the lack of an application at the destination port.\n\nDiscontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by discontinuities in the value of sysUpTime.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1482 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "udpInErrors", "name": "udpInErrors" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "udpNoPorts", "name": "udpNoPorts" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "$hrStorage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1491 },
   "repeat": "hrStorage",
   "targets": [
    {}
   ]
  },
  {
   "title": "hrStorage[$hrStorage]",
   "type": "timeseries",
   "description": "**hrStorageAllocationUnits**: The size, in bytes, of the data objects allocated from this pool.  If this entry is monitoring sectors, blocks, buffers, or packets, for example, this number will commonly be greater than one.  Otherwise this number will typically be one.\n\n**hrStorageSize**: The size of the storage represented by this entry, in units of hrStorageAllocationUnits. This object is writable to allow remote configuration of the size of the storage area in those cases where such an operation makes sense and is possible on the underlying system. For example, the amount of main memory allocated to a buffer pool might be modified or\nthe amount of disk space allocated to virtual memory might be modified.\n\n**hrStorageUsed**: The amount of the storage represented by this entry that is allocated, in units of hrStorageAllocationUnits.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1492 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrStorageSize", "name": "hrStorageSize" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "hrStorageIndex[$hrStorage]", "label": "hrStorageIndex[$hrStorage]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrStorageUsed", "name": "hrStorageUsed" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "hrStorageIndex[$hrStorage]", "label": "hrStorageIndex[$hrStorage]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrStorageAllocUnits", "name": "hrStorageAllocUnits" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "hrStorageIndex[$hrStorage]", "label": "hrStorageIndex[$hrStorage]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "expression": "hrStorageSize * hrStorageAllocUnits",
     "label": "Size",
     "performanceType": { "label": "Expression", "value": 2 }
    },
    {
     "expression": "hrStorageUsed * hrStorageAllocUnits",
     "label": "Used",
     "performanceType": { "label": "Expression", "value": 2 }
    },
    {
     "filter": {
      "backend": "R",
      "canonicalName": "org.opennms.netmgt.measurements.filters.impl.TrendLine",
      "description": "Fits a trend line or polynomial to a given column.",
      "label": "Trend",
      "name": "Trend",
      "parameter": [
       {
        "description": "Input column.",
        "displayName": "Input",
        "key": "inputColumn",
        "required": true,
        "type": "string"
       },
       {
        "description": "Output column.",
        "displayName": "Output",
        "key": "outputColumn",
        "required": true,
        "type": "string"
       },
       {
        "default": "0",
        "description": "Number seconds ahead the of the column for which we want to include the trend line.",
        "displayName": "Forecast",
        "key": "secondsAhead",
        "required": true,
        "type": "long"
       },
       {
        "default": "1",
        "description": "Polynomial order of the trend line/curve. Set this to 1 for a line.",
        "displayName": "Order",
        "key": "polynomialOrder",
        "required": true,
        "type": "int"
       }
      ]
     },
     "filterState": {
      "inputColumn": {
       "filter": {
        "description": "Input column.",
        "displayName": "Input",
        "key": "inputColumn",
        "required": true,
        "type": "string"
       },
       "value": "Used"
      },
      "outputColumn": {
       "filter": {
        "description": "Output column.",
        "displayName": "Output",
        "key": "outputColumn",
        "required": true,
        "type": "string"
       },
       "value": "Trend"
      },
      "secondsAhead": {
       "filter": {
        "description": "Number seconds ahead the of the column for which we want to include the trend line.",
        "displayName": "Forecast",
        "key": "secondsAhead",
        "required": true,
        "type": "long"
       },
       "value": "7200"
      }
     },
     "performanceType": { "label": "Filter", "value": 3 }
    }
   ]
  },
  {
   "title": "Linux monitoring sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1539 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature lmTempIndex[$lmTempIndex]",
   "type": "timeseries",
   "description": "**lmTempSensorsValue**: The temperature of this sensor in mC.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1540 },
   "repeat": "lmTempIndex",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "lms-temp", "name": "lms-temp" },
      "fallbackAttribute": {},
      "label": "temp",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "lmTempIndex[$lmTempIndex]", "label": "lmTempIndex[$lmTempIndex]" }
     },
     "label": "temp",
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    {
     "expression": "temp / 1000.0",
     "label": "resourceToLabel($node, lmTempIndex[$lmTempIndex])",
     "performanceType": { "label": "Expression", "value": 2 }
    }
   ]
  },
  {
   "title": "System statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1547 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of users",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1548 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrSystemNumUsers", "name": "hrSystemNumUsers" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1548 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrSystemProcesses", "name": "hrSystemProcesses" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1548 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "attribute": {
      "aggregation": { "label": "" },
      "attribute": { "label": "hrSystemUptime", "name": "hrSystemUptime" },
      "fallbackAttribute": {},
      "label": "",
      "node": { "id": "$node", "label": "$node" },
      "resource": { "id": "nodeSnmp[]", "label": "nodeSnmp[]" }
     },
     "performanceType": { "label": "Attribute", "value": 1 }
    },
    { "expression": "hrSystemUptime / 100", "label": "Uptime", "performanceType": { "label": "Expression", "value": 2 } }
   ]
  }
 ]
}